"""On-demand Robinhood position sync.

Run from the Mac terminal after a trade. Logs into Robinhood (prompts for
SMS/MFA code interactively when required — robin_stocks pickles the session
so the prompt only happens occasionally), pulls open option positions, and
writes three tabs to the Google Sheet:

  - Positions      : auto-written mirror of Robinhood's open option positions
  - Config         : auto-generated by matching Positions to Sheet1 rows on
                     (Symbol, Expiration). Drives the daily price pipeline.
  - Reconciliation : lists every Robinhood position that has no Sheet1 row
                     (you need to add one) and every Sheet1 row with no
                     Robinhood match (you probably closed it). Empty means
                     everything's in sync.

Sheet1 stays hand-curated — this script never touches it.
"""
from __future__ import annotations

import logging
import os
import sys
from datetime import datetime
from typing import Optional

import robin_stocks.robinhood as r
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("sync")

SHEETS_SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]
POSITIONS_TAB = "Positions"
CONFIG_TAB = "Config"
RECON_TAB = "Reconciliation"
MAIN_TAB = "Sheet1"
SHEET1_SCAN_RANGE = "Sheet1!A1:F100"  # A=Symbol, B=Expiration, F=Current price/contract


def env(name: str, required: bool = False, default: str = "") -> str:
    val = os.environ.get(name, default)
    if required and not val:
        log.error("missing env var: %s", name)
        sys.exit(2)
    return val


def login() -> None:
    user = env("ROBINHOOD_USERNAME", required=True)
    pwd = env("ROBINHOOD_PASSWORD", required=True)
    log.info("Logging into Robinhood... (you may be prompted for a 2FA code)")
    r.login(user, pwd)
    log.info("Logged in")


def fetch_market_price(option_id: str) -> Optional[float]:
    """Return current mark price per CONTRACT (mark × 100) for an option, or None."""
    try:
        mkt = r.options.get_option_market_data_by_id(option_id)
    except Exception as e:
        log.warning("market_data fetch failed for %s: %s", option_id, e)
        return None
    if not mkt:
        return None
    m = mkt[0] if isinstance(mkt, list) else mkt
    # Prefer mark, fall back to last_trade, then mid-of-bid/ask
    for key in ("mark_price", "adjusted_mark_price", "last_trade_price"):
        v = m.get(key)
        if v not in (None, "", "0", "0.0", "0.00", "0.000000"):
            try:
                return float(v) * 100
            except (ValueError, TypeError):
                pass
    bid, ask = m.get("bid_price"), m.get("ask_price")
    if bid and ask:
        try:
            return ((float(bid) + float(ask)) / 2.0) * 100
        except (ValueError, TypeError):
            pass
    return None


def fetch_positions() -> list[dict]:
    account_number = env("ROBINHOOD_ACCOUNT_NUMBER") or None
    raw = r.options.get_open_option_positions(account_number=account_number)
    log.info("Robinhood returned %d open option position(s) for account %s",
             len(raw), account_number or "(default)")
    positions = []
    for p in raw:
        try:
            qty = float(p.get("quantity") or 0)
        except (TypeError, ValueError):
            qty = 0.0
        if qty == 0:
            continue
        instrument_url = p.get("option")
        if not instrument_url:
            log.warning("position has no instrument URL, skipping: %r", p)
            continue
        details = r.helper.request_get(instrument_url)
        if not details:
            log.warning("could not fetch instrument %s, skipping", instrument_url)
            continue
        option_id = instrument_url.rstrip("/").split("/")[-1]
        side_sign = -1 if p.get("type") == "short" else 1
        current = fetch_market_price(option_id)
        positions.append({
            "underlying": details["chain_symbol"],
            "expiration": details["expiration_date"],
            "strike": float(details["strike_price"]),
            "type": details["type"][0].upper(),
            "quantity": qty * side_sign,
            "avg_price": float(p.get("average_price") or 0),
            "current": current,  # per-contract dollars (mark × 100)
        })
    return positions


def occ_symbol(p: dict) -> str:
    y, m, d = p["expiration"].split("-")
    return f"O:{p['underlying'].upper()}{y[-2:]}{m}{d}{p['type']}{int(round(p['strike'] * 1000)):08d}"


def sheets_service():
    creds = Credentials.from_service_account_file(
        env("GOOGLE_APPLICATION_CREDENTIALS", required=True), scopes=SHEETS_SCOPES
    )
    return build("sheets", "v4", credentials=creds, cache_discovery=False)


def ensure_tabs(svc, sheet_id: str, tab_names: list[str]) -> None:
    meta = svc.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing = {s["properties"]["title"] for s in meta["sheets"]}
    to_create = [t for t in tab_names if t not in existing]
    if not to_create:
        return
    svc.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": t}}} for t in to_create]},
    ).execute()
    log.info("Created missing tabs: %s", to_create)


def write_tab(svc, sheet_id: str, tab: str, values: list[list]) -> None:
    # Look up the sheetId for this tab name (needed for formatting reset)
    meta = svc.spreadsheets().get(spreadsheetId=sheet_id).execute()
    sheet_id_int = next(s["properties"]["sheetId"] for s in meta["sheets"]
                        if s["properties"]["title"] == tab)
    # Reset cell formatting in one shot, otherwise old column formats (like a date
    # format inherited from a prior schema) make new numeric values display wrong.
    svc.spreadsheets().batchUpdate(spreadsheetId=sheet_id, body={"requests": [{
        "updateCells": {
            "range": {"sheetId": sheet_id_int},
            "fields": "userEnteredFormat,userEnteredValue",
        }
    }]}).execute()
    svc.spreadsheets().values().update(
        spreadsheetId=sheet_id, range=f"{tab}!A1",
        valueInputOption="USER_ENTERED", body={"values": values},
    ).execute()


def parse_sheet_expiration(s: str) -> Optional[str]:
    """Normalize Sheet1's date strings (5/15, 1/15/27, 2026-05-15) -> ISO YYYY-MM-DD."""
    s = s.strip()
    if not s:
        return None
    # ISO already
    if len(s) == 10 and s[4] == "-" and s[7] == "-":
        return s
    parts = s.split("/")
    try:
        if len(parts) == 2:
            m, d = int(parts[0]), int(parts[1])
            # Heuristic: if month already passed by 6+ months, assume next year
            now = datetime.now()
            year = now.year + (1 if m < now.month - 6 else 0)
            return f"{year}-{m:02d}-{d:02d}"
        if len(parts) == 3:
            m, d, y = int(parts[0]), int(parts[1]), int(parts[2])
            year = y + 2000 if y < 100 else y
            return f"{year}-{m:02d}-{d:02d}"
    except (ValueError, IndexError):
        return None
    return None


def read_sheet1_contracts(svc, sheet_id: str) -> list[dict]:
    """Pull (row, symbol, expiration, current_price) tuples from Sheet1. Filters
    to rows whose column B parses as a date — skips the deposit log, totals
    row, headers, etc. current_price comes from column F (per-contract dollars,
    populated daily by the price routine); None when blank/non-numeric."""
    resp = svc.spreadsheets().values().get(spreadsheetId=sheet_id, range=SHEET1_SCAN_RANGE).execute()
    out = []
    for i, row in enumerate(resp.get("values", []), start=1):
        if len(row) < 2:
            continue
        sym = (row[0] or "").strip()
        exp_raw = (row[1] or "").strip()
        if not sym or not exp_raw:
            continue
        if parse_sheet_expiration(exp_raw) is None:
            continue
        current = None
        if len(row) >= 6:
            try:
                current = float(str(row[5]).replace(",", "").strip())
            except (ValueError, TypeError):
                current = None
        out.append({"row": i, "symbol": sym, "expiration_raw": exp_raw, "current": current})
    return out


def match(positions: list[dict], sheet_contracts: list[dict]):
    """Match each position to a Sheet1 row by (symbol, normalized expiration).

    Returns (matches, unmatched_positions, orphaned_sheet_rows).
      matches: list of (position, sheet_row_num)
      unmatched_positions: list of (position, num_candidates_in_sheet)
      orphaned_sheet_rows: list of sheet_contracts with no matching position
    """
    remaining = list(sheet_contracts)
    matches = []
    unmatched = []
    for p in positions:
        cands = [s for s in remaining
                 if s["symbol"].upper() == p["underlying"].upper()
                 and parse_sheet_expiration(s["expiration_raw"]) == p["expiration"]]
        if len(cands) == 1:
            matches.append((p, cands[0]["row"]))
            remaining.remove(cands[0])
        else:
            unmatched.append((p, len(cands)))
    return matches, unmatched, remaining


def main() -> int:
    sheet_id = env("SHEET_ID", required=True)
    login()
    positions = fetch_positions()

    svc = sheets_service()
    ensure_tabs(svc, sheet_id, [POSITIONS_TAB, CONFIG_TAB, RECON_TAB])

    # --- Positions tab: live Robinhood positions + current mark + P/L ---
    pos_header = ["Ticker", "Strike", "Expiry", "Put/Call", "Avg Buying Price",
                  "No of Cons", "Current Price", "Profit/Loss"]
    pos_rows = []
    for p in positions:
        avg_unsigned = abs(p["avg_price"])
        qty_signed = int(p["quantity"]) if p["quantity"].is_integer() else p["quantity"]
        current = p.get("current")
        if current is not None:
            if p["quantity"] > 0:
                pl = (current - avg_unsigned) * abs(p["quantity"])
            else:
                pl = (avg_unsigned - current) * abs(p["quantity"])
            current_disp = round(current)
            pl_disp = round(pl)
        else:
            current_disp = ""
            pl_disp = ""
        pos_rows.append([
            p["underlying"], p["strike"], p["expiration"], p["type"],
            round(avg_unsigned, 2), qty_signed, current_disp, pl_disp,
        ])
    write_tab(svc, sheet_id, POSITIONS_TAB, [pos_header] + pos_rows)
    log.info("Wrote Positions tab: %d row(s)", len(pos_rows))

    # --- Match to Sheet1 for Config + Reconciliation tabs (unchanged) ---
    sheet_contracts = read_sheet1_contracts(svc, sheet_id)
    matches, unmatched_pos, orphaned_rows = match(positions, sheet_contracts)

    cfg_header = ["Underlying", "Expiration", "Strike", "Type", "MainSheetRow"]
    cfg_rows = [[p["underlying"], p["expiration"], p["strike"], p["type"], row] for p, row in matches]
    write_tab(svc, sheet_id, CONFIG_TAB, [cfg_header] + cfg_rows)
    log.info("Wrote Config tab: %d matched contract(s)", len(cfg_rows))

    recon_header = ["Issue", "Underlying", "Expiration", "Details"]
    recon_rows = []
    for p, count in unmatched_pos:
        if count == 0:
            recon_rows.append(["Open position in Robinhood, no Sheet1 row — ADD ROW",
                               p["underlying"], p["expiration"],
                               f"strike={p['strike']} type={p['type']} qty={p['quantity']:+g} avg=${p['avg_price']:.2f}"])
        else:
            recon_rows.append([f"Ambiguous: {count} Sheet1 rows match this contract",
                               p["underlying"], p["expiration"],
                               f"strike={p['strike']} type={p['type']} qty={p['quantity']:+g}"])
    for s in orphaned_rows:
        recon_rows.append(["Sheet1 row has no Robinhood position — CLOSED?",
                           s["symbol"], s["expiration_raw"], f"Sheet1 row {s['row']}"])
    if recon_rows:
        write_tab(svc, sheet_id, RECON_TAB, [recon_header] + recon_rows)
        log.warning("Reconciliation tab has %d issue(s) — review the sheet", len(recon_rows))
    else:
        write_tab(svc, sheet_id, RECON_TAB, [recon_header, ["(all positions matched — nothing to do)"]])
        log.info("Reconciliation tab is clean — all positions matched")

    log.info("Sync complete: %d matched, %d unmatched, %d orphaned",
             len(matches), len(unmatched_pos), len(orphaned_rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
